Initial akamai sdk set up
launchdarkly/js-core pull request #121
Opened 2023-05-23 16:08 UTC by dariushar

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

2023-05-23 17:36 UTC, ctawiah approved these changes
This looks good to me but looks like we'll need an approval from someone on the SDK team as well.

2023-05-24 21:56 UTC, kinyoklion commented on packages/sdk/akamai/LICENSE
> +Copyright 2022 Catamorphic, Co.
2023

2023-05-24 21:58 UTC, kinyoklion commented on release-please-config.json
> +    "packages/sdk/akamai": {},
You may want to avoid putting this into the release-please config until you are ready for it to be released. Otherwise it will start getting released. :-)

2023-05-24 21:59 UTC, kinyoklion requested changes
I would remove it from the release please config until you are ready to release it.

2023-05-24 22:11 UTC, dariushar commented on packages/sdk/akamai/LICENSE
> +Copyright 2022 Catamorphic, Co.
Fixed!

2023-05-24 22:11 UTC, dariushar commented on release-please-config.json
> +    "packages/sdk/akamai": {},
Updated!

2023-05-24 22:12 UTC, kinyoklion approved these changes

2023-05-24 22:18 UTC, merged