chore: file changes after prettier update
launchdarkly/js-core pull request #209
Opened 2023-07-19 22:29 UTC by yusinto

This PR is the result of running prettier v3 #208 on all files in the codebase.

2023-07-24 16:04 UTC, kinyoklion requested changes

2023-07-28 21:56 UTC, yusinto commented on packages/sdk/akamai-edgekv/src/edgekv/edgekv.js
> -import { TextDecoderStream } from 'text-encode-transform';
This file is an anomaly. Firstly it's in `.js` and not `.ts` so it's' type and lint skipped very worryingly. If this file was linted, it will not have passed linting because the `edgekv_tokens.js` import does not exist. I think this entire file was copied from Akamai and its contents are purely from an external source.

Coming back to this pr though, grouping works and it looks like [this](https://github.com/launchdarkly/js-core/blob/277ce7070271fbc738346638dc28acc486e4e106/packages/sdk/akamai-edgekv/src/edgekv/edgeKVProvider.ts#L3):

```ts
import { EdgeProvider } from '@launchdarkly/akamai-edgeworker-sdk-common';

import { EdgeKV } from './edgekv';

type EdgeKVProviderParams = {
  namespace: string;
  group: string;
};
```

2023-07-28 22:07 UTC, yusinto commented on packages/sdk/akamai-base/CHANGELOG.md
> +- The following workspace dependencies were updated
Done. I've excluded all changelogs.

2023-07-28 22:08 UTC, yusinto commented on packages/sdk/akamai-edgekv/src/edgekv/edgekv.js
> -import { TextDecoderStream } from 'text-encode-transform';
I'm excluding this file from prettier because it seems this is a third party external file which we duplicated and so may want to maintain in its original form.

2023-07-28 22:33 UTC, yusinto commented on packages/sdk/vercel/examples/complete/components/launchdarklyProvider.tsx
> +// The "use client" is necessary here because the LaunchDarkly React SDK returns a client-side component
I spent time looking into this. `use client` is a non-standard [directive specific only to nextjs](https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive) ssr apps. Prettier does not understand this so it does its best.

I have modified the location of the comments to be above the exported function, with updated description to refer and explain this non-standard directive.

2023-07-28 22:52 UTC, kinyoklion commented on .release-please-manifest.json
> +{
I don't know if this will cause problems. I guess we will find out when we release it.

2023-07-28 22:58 UTC, kinyoklion approved these changes

2023-07-28 22:59 UTC, merged