Enable the option to send events in Vercel SDK
launchdarkly/js-core pull request #217
Opened 2023-07-31 13:02 UTC by ldhenry

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

2023-07-31 15:55 UTC, kinyoklion commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
This will break local linking for all the edge SDKs. I would prefer we never make manual changes to any of the package.json files, but I do see how it could be unavoidable sometimes. 

Generally these should be handled by the conventional commit tags and the "release-as" settings. 

The way this is right now the other SDKs are linking against the release version because the local version doesn't match what is in the repository. This means that testing those will be all kinds of inconsistent.

2023-07-31 16:00 UTC, kinyoklion reviewed
I commented incorrectly. Didn't realize fetch was implemented, just didn't get called.

2023-07-31 16:09 UTC, kinyoklion commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
I think you can revert these now that you published your pre-release. Then release please will update them based on your conventional commit. Importantly it will also update all the other edge SDKs.

2023-07-31 16:11 UTC, ldhenry commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
I just did this as so I could run the manual Release Github workflow on this branch. I will revert this change if/when we merge this into `main`.

Can you give me an example of how to do this with a conventional commit tag without merging this PR into main?

2023-07-31 16:11 UTC, ldhenry commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
Cool. I'll revert now.

2023-07-31 16:13 UTC, kinyoklion commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
So, if you want to release from a branch, as you did, then that is fine. But it is in PR against main now, so I have to be explicit.

2023-07-31 16:15 UTC, ldhenry commented on packages/shared/sdk-server-edge/package.json
> +  "version": "1.1.0-alpha.0",
Makes sense. Thanks for your help.

2023-07-31 18:12 UTC, ldhenry commented
I added DO NOT MERGE to the title because we are waiting on customer feedback of the beta build.

2023-08-14 23:24 UTC, kinyoklion commented
@ldhenry The user agent change is now merged, so you can remove the wrapper name/version.

2023-08-25 08:27 UTC, yusinto commented on packages/sdk/vercel/src/index.ts
> + *  The client-side ID. This is only used to query the edgeConfig above,
Can we use the `sdkKey` use that to both query edgeConfig and also connect to streamer to send events? This reduces confusion having both clientSideID and serverSideKey which seems redundant to me.

2023-08-25 08:29 UTC, yusinto requested changes

2023-08-25 08:29 UTC, yusinto commented on packages/shared/sdk-server-edge/src/utils/validateOptions.ts
> +};
As I mentioned [above](https://github.com/launchdarkly/js-core/pull/217/files#r1305357502), we can avoid this additional option if we just reuse `sdkKey`. I think it's do-able.

2023-08-25 08:50 UTC, ldhenry commented on packages/sdk/vercel/src/index.ts
> + *  The client-side ID. This is only used to query the edgeConfig above,
Unfortunately the env data is stored in the edge config DB under the client side ID so we need both

2023-08-25 15:23 UTC, kinyoklion commented on packages/sdk/vercel/src/index.ts
> + *  The client-side ID. This is only used to query the edgeConfig above,
As a secondary note I don't think you would want to use the SDK key for this, even if it was starting now. If the SDK key was used to store the edge config, then you would create some tricky situations if you wanted to rotate the SDK key. Client side ID is fixed.

(Though I would have overall preferred some identifier that wasn't the client-side ID. Simply because this makes it really conceptually confusing.)

2023-08-25 15:26 UTC, ldhenry commented on packages/sdk/vercel/src/index.ts
> + *  The client-side ID. This is only used to query the edgeConfig above,
yup - maybe we could eventually use something like `projectKey:envKey` for this but it would be a pretty big hassle to migrate over.

2023-08-30 14:20 UTC, ldhenry commented
Closing in favor of #256

2023-08-30 14:20 UTC, closed without merging