feat: edge sdks should send events to bulk/environment endpoint
launchdarkly/js-core pull request #256
Opened 2023-08-26 06:43 UTC by yusinto

Edge sdks use clientSideID not sdk-key. We should be able to post events to the eventsUri/bulk/clientSideID endpoint for edge sdks without needing to specify the sdk key in the authorization header.

2023-08-26 07:00 UTC, yusinto commented on packages/shared/sdk-server/src/events/EventSender.ts
> +      : `${events}/diagnostic`;
Use the appropriate endpoints based on [this](https://launchdarkly.atlassian.net/wiki/spaces/PD/pages/2129461878/Service+endpoints+used+by+SDKs).

2023-08-26 07:03 UTC, yusinto commented
I still need to test this PR in a real application but based on existing js sdk code, this PR should work.

2023-08-28 02:36 UTC, yusinto commented on packages/sdk/cloudflare/example/src/index.ts
> +    });
GOTCHA: critical to flush otherwise events are not going to be sent.

2023-08-28 02:36 UTC, yusinto commented on packages/shared/sdk-server/src/events/EventSender.ts
> +      this.logger?.error(`===== events: ${JSON.stringify(events)}`);
Debugging only and will remove prior to merging.

2023-08-28 02:36 UTC, yusinto commented on scripts/build-doc.sh
> +#!/bin/bash
Locally `yarn build` failed with a weird yarn error without these.

2023-08-28 02:36 UTC, yusinto commented on packages/sdk/cloudflare/example/src/index.ts
> +    const clientSideID = '59b2b2596d1a250b1c78baa4';
Debugging only and will remove prior to merging.

2023-08-28 02:36 UTC, yusinto commented on link-dev.sh
The cloudflare example app doesn't work with modern yarn workspaces so I have to do this manually.

2023-08-28 02:37 UTC, yusinto commented
I ran the cloudflare example app using this code which uses clientSideID and events seem to be sent.

<img width="959" alt="Screenshot 2023-08-27 at 7 36 47 PM" src="https://github.com/launchdarkly/js-core/assets/1593077/331be152-b4ba-4b70-ad91-d2ef257e6423">

2023-08-28 16:04 UTC, kinyoklion commented
I am not sure about this. The events that can be generated from a client SDK are not 100% the same. So I do not know how the endpoints for a client SDK handle the data.

The server-side SDKs, which these are, generate prerequisite record events. Would the client SDK endpoint for events handle those correctly? If we have a definitive answer, then I can see pursuing it.

2023-08-28 16:05 UTC, kinyoklion commented
Secondarily it appears these changes break many contract tests, so some investigation is need there.

2023-08-28 16:09 UTC, kinyoklion commented on packages/shared/sdk-server/src/data_sources/defaultHeaders.ts
> +  }
This far SDK keys have been opaque to the SDK, so likely this will cause problems in testing infrastructure. It may be why the contract tests break. I think we would need some discussions to agree to the SDKs treating keys as non-opaque.

2023-08-28 16:15 UTC, kinyoklion commented on packages/shared/sdk-server/src/events/EventSender.ts
> +      : `${events}/diagnostic`;
Similarly uncomfortable with this change. If we want to do something like this, then likely we should move the full URL to earlier config. Then use another piece of either config or platform to control it.

At the most basic level `SdkAuthType` which has `Mobile`, `Server`, `ClientSide`. This would get similarly messy if we add more hybrid SDKs like these edge SDKs. 

At the more complex side just make a function that can be provided by the SDK implementation to get the endpoints. I would generally prefer this, edge SDKs can control their destiny and don't have to have implementation details reaching as deep. It also would allow for more runtime config, which could happen for something like RN (if an SDK ever supports RN and web targets).

2023-08-28 18:21 UTC, yusinto commented
Thanks for your feedback. I submitted this PR having done due diligence checking the event recorder logic how it handles events for server and client sdks.

My investigation reveals both the [/bulk](https://github.com/launchdarkly/event-recorder/blob/89b0dc55660d31473f5b4345a0623f85806afd47/event-recorder/event-recorder.go#L814) and [/events/bulk/{envId}](https://github.com/launchdarkly/event-recorder/blob/89b0dc55660d31473f5b4345a0623f85806afd47/event-recorder/event-recorder.go#L833) endpoints are handled equally by the [postBulkEvents](https://github.com/launchdarkly/event-recorder/blob/89b0dc55660d31473f5b4345a0623f85806afd47/event-recorder/event-recorder.go#L136) handler. You'll see this postBulkEvents contain the [RecordRequest](https://github.com/launchdarkly/event-recorder/blob/89b0dc55660d31473f5b4345a0623f85806afd47/event-recorder/event-recorder.go#L141) logic you are concerned with so I think this is covered for both server and client sdks.

I understand your concerns though and you want us to be thorough with this kind of hybrid logic because we never had to mix the two before. The edge sdks are unique in this way, it is truly somewhat of a hybrid. This approach opens the door for the future for such sdks so I'm hopeful this works. I will assign someone from the events pipeline to review my work.

I will investigate the contract tests failures, I suspect they are related to the `sdk-` key prefix which is necessary now. If those tests use some arbitrary strings as sdkKey then those will fail.

2023-08-28 19:10 UTC, yusinto commented
Added @samstokes as reviewer from the Events pipeline team.

2023-08-28 20:45 UTC, samstokes reviewed
LGTM from an event pipeline standpoint. (Leaving it to the SDK team to do the approving.)

Re:
> The events that can be generated from a client SDK are not 100% the same. So I do not know how the endpoints for a client SDK handle the data.

I can confirm that both endpoints behave identically in terms of what event payloads they will accept. e.g. even though only browser SDKs generate `click` events, the `/bulk` endpoint that handles server-side SDK payloads will happily accept a `click` event. It all goes into the same Kinesis stream :)

Re the specific concern about prerequisite events:
> The server-side SDKs, which these are, generate prerequisite record events. Would the client SDK endpoint for events handle those correctly? If we have a definitive answer, then I can see pursuing it.

I don't think anything in our event pipeline does anything special with prerequisites. Definitely the events endpoint handlers don't.

(AFAIK there's nothing special about prerequisite _events_, right - they're just regular evaluation events? And the only special consideration is that client-side SDKs don't send them.

2023-08-28 20:45 UTC, samstokes commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
This suggests that this change might have broader implications than just sending events. If the SDK uses a client-side id rather than SDK key _for authentication to the flag delivery services_ (streamer and flagbearer), it will actually receive different information - it'll need to specify user attributes along with the call, and will receive evaluated flag payloads for that user, rather than the flag evaluation ruleset.

I am guessing this actually means this comment is stale, rather than an actual change in behavior, because I assume the SDK has already been modified to get flag values from the edge store rather than the flag delivery endpoints.

I find this comment confusing, though, and possibly misleading - could we update it to clarify what if anything the client-side id is actually used for here?

2023-08-28 20:45 UTC, samstokes commented on packages/shared/sdk-server/src/events/EventSender.ts
> +      : `${events}/diagnostic`;
I'll defer to y'all to decide on code organization, but just to agree from a security standpoint it'd be nice if there was a clearer distinction between `sdkKey` and `clientSideID` in the code, rather than storing them both in a variable called `sdkKey` and relying on just a prefix to disambiguate them. _(Not a blocker for me, just a +1 to the existing comment.)_

SDK keys are sensitive and client-side IDs are not, and it'd be bad if we accidentally sent an SDK key in a URL - which aren't generally treated as sensitive, and could get copy-pasted, logged by proxies, etc.

2023-08-28 20:49 UTC, kinyoklion commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
It is indeed confusing. Edge SDKs operate as server SDKs, but they don't connect to LD to get the flag configuration. They are similar to daemon mode. The expectation is that some edge specific store contains the flag configuration. At some point it was decided that the flag configuration would be stored by the client side ID. So the client side ID is the key, or component of the key, where the flag configuration is stored.

2023-08-28 20:50 UTC, kinyoklion commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
So, they have to have that ID already. So it is ideal if they can also use it for events. There is another PR which takes both keys and uses them for different purposes.

2023-08-28 20:55 UTC, samstokes commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
I see. Maybe this is because the client-side ID is also the environment id, which is the logical "owner" of the flag configuration? I guess I retract my suggestion to update the comment. (Maybe the previous wording which said that the SDK key was "used to query featureStore" was incorrect?)

2023-08-28 21:03 UTC, yusinto commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
```suggestion
  // clientSideID is only used to query featureStore and send analytics, not to initialize with LD servers
  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
```

2023-08-28 21:10 UTC, kinyoklion commented on packages/shared/sdk-server-edge/src/api/LDClient.ts
> +  constructor(clientSideID: string, platformInfo: Info, options: LDOptions) {
I think the problem is that featureStore is a bit confusing. It is used to initialize the special edge SDK feature store. It isn't really used to query it. It is used to query the edge key-value store.

2023-08-28 21:23 UTC, yusinto commented
> from a security standpoint it'd be nice if there was a clearer distinction between sdkKey and clientSideID in the code

Thanks @samstokes ! I have improved the code to provide a better distinction between sdkKey and clientSideID.

2023-08-28 21:35 UTC, kinyoklion approved these changes

2023-08-29 18:40 UTC, ldhenry reviewed
This looks great @yusinto. Thanks or confirming the client-side endpoint can handle all of the events correctly. Before merging and releasing, I think it would be good to publish a pre-release version so we can test it in a deployed environment. I ran out of time today but I can give it a shot tomorrow.

2023-08-29 19:04 UTC, yusinto commented
Thanl you @ldhenry ! I'll go ahead and do a pre-release. Right now the cloudflare sdk is at 2.1.3. I think this should just be a minor release, so I'll release 2.2.0-alpha. Any objections?

2023-08-29 20:08 UTC, yusinto commented on release-please-config.json
> +      "release-as": "1.2.0-alpha"
@kinyoklion are these correct? Is there anymore I need to do for an alpha release?

2023-08-30 14:24 UTC, ldhenry requested changes

2023-08-30 14:24 UTC, ldhenry commented on packages/sdk/cloudflare/example/src/index.ts
> +    await client.flush((err, res) => {
Let's put this inside of a [`context.waitUntil`](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil) to show customers how to flush events without impacting the handler's response time.

2023-08-30 14:24 UTC, ldhenry commented on packages/sdk/cloudflare/example/src/index.ts
>    async fetch(request: Request, env: Bindings): Promise<Response> {
We'll need to add the context argument to leverage the [`waitUntil` method](https://developers.cloudflare.com/workers/runtime-apis/fetch-event/#waituntil) (more detail below).
```suggestion
  async fetch(request: Request, env: Bindings, context: ExecutionContext): Promise<Response> {
```

2023-09-05 18:15 UTC, yusinto commented
@ldhenry pls re-review when able. Thank you

2023-09-08 13:56 UTC, ldhenry commented
> @ldhenry pls re-review when able. Thank you

Hey @yusinto, I was hoping to get some sort of evidence that this is working from our alpha customers before making this more widely available. However, I can't see any usage in [honeycomb](https://ui.honeycomb.io/launchdarkly/datasets/production/result/koC6r4UCrvH?hideMarkers). Do you know if there is a better way to see adoption?

2023-09-13 22:00 UTC, yusinto commented
> Do you know if there is a better way to see adoption?

Yep we can try querying cmetrics directly following [these instructions](https://launchdarkly.atlassian.net/wiki/spaces/ENG/pages/2192638480/SDK+Notifications+Phase+1+Tech+Spec).

2023-09-15 20:34 UTC, samstokes reviewed
Nothing to add, just commenting so GitHub will stop reminding me about this PR. If there's anything that does need my feedback please feel free to "re-request review".

2023-11-09 19:53 UTC, louis-launchdarkly approved these changes

2023-11-09 20:30 UTC, mmrj commented on packages/sdk/cloudflare/example/src/index.ts
To the Vercel and/or Akamai examples also need to be updated? I initially thought this change only applied to Cloudflare because only the Cloudflare example was changed.

2023-11-12 03:02 UTC, yusinto commented on packages/sdk/cloudflare/example/src/index.ts
Those examples can be updated, but not necessary. I'll leave that to @ldhenry .

2023-11-12 03:03 UTC, yusinto commented
@ldhenry please approve so this can be merged. Thank you.

2023-11-12 22:56 UTC, ldhenry approved these changes

2023-11-12 22:56 UTC, merged