Yus/1 share stream
launchdarkly/js-core pull request #275
Opened 2023-09-12 18:48 UTC by yusinto

wip

2023-09-12 22:30 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
Note: this file is to be deleted. This is only here to facilitate easier review because [this file has been moved](https://github.com/launchdarkly/js-core/pull/275#discussion_r1323615977) to shared/common and github doesn't show the diff clearly.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
>    ) {
* `config` is removed replaced with clientContext to get required application tags for http header creation.
* Constructor now accepts listeners so client and server sdks can have custom logic to handle stream events.
* `featureStore` is no longer required because the listeners above will deal with featureStores.
* New addition of `errorHandler` to handle all stream errors rather than passing a callback to the start function.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> -  start(fn?: ((err?: any) => void) | undefined) {
I have removed this callback because it is confusing. It served a dual purpose of handling errors and simultaneously handling init success. I hope to remove this confusion with a clearer interface by:
* introducing an explicit errorHandler specified at construction time
* introducing custom `listeners` at construction time which is responsible for handling successes.

Refer to my comments above regarding these two.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> -        fn?.(new LDStreamingError(err.message, err.status));
Now we use an explicit errorHandler specified at construction time.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> -
This has been moved outside of this class to reduce the size of the class. In the future we can move this out of this file entirely to reduce the file size.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> -    });
Event listener logic are the client/server sdk's responsibility. For the server sdk, it has been moved to [createStreamListeners](https://github.com/launchdarkly/js-core/blob/30e8d61ef79678e52599385ad787c63e26ee63af/packages/shared/sdk-server/src/data_sources/createStreamListeners.ts#L19). Each listener must specify two things: a deserialization and a processJson callback.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> +          const dataJson = deserializeData(data);
Each sdk specifies its own `deserializeData` logic.

2023-09-12 22:56 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> +          processJson(dataJson);
And consequently each sdk specifies its own logic how to process the deserialized data.

2023-09-12 23:06 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/createStreamListeners.ts
> +    dataSourceUpdates.init(initData, onPutCompleteHandler);
Note `onPutCompleteHandler` is the replacement of the success callback [removed](https://github.com/launchdarkly/js-core/pull/275/files#r1323684022) in the `start` function. In fact all listeners now have a choice to specify their own callbacks.

2023-09-12 23:06 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/createStreamListeners.ts
> +  },
Previously, the `put` handler invokes a success init callback. This is a very specific logic which I have generalized here for future benefit and flexibility. By allowing all listeners to specify their own onComplete callbacks, each individual sdk and listener can choose how to respond to any kind of event (not just put) on completion.

2023-09-13 00:17 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/StreamingProcessor.ts
> -}
This has been moved to `packages/shared/sdk-server/src/store/VersionedDataKinds.ts`

2023-09-13 00:17 UTC, yusinto commented on packages/shared/sdk-server/src/LDClientImpl.ts
> -
This is not deleted but moved below to group update processor logic together. 

Note though I have deleted `NullUpdateProcessor` because its purpose seemed to only make `updateProcessr.start()` wait one tick. This logic is now in this file (see below).

2023-09-13 04:58 UTC, yusinto commented on packages/shared/common/src/api/options/LDClientContext.ts
> +  tags?: { value?: string };
Added streamInitialReconnectDelay and tags for easy sharing between internal components of client and server sdks.

2023-09-13 05:16 UTC, yusinto commented on packages/shared/common/src/api/subsystem/LDStreamProcessor.ts
> -  start: (fn?: (err?: any) => void) => void;
This callback has been removed in favor of a cleaner separation of concern between error handling and success handling. This is further explained in detail [here](https://github.com/launchdarkly/js-core/pull/275/files#r1323684022) and throughout this pr.

2023-09-13 05:16 UTC, yusinto commented on packages/shared/common/src/api/platform/EventSource.ts
> +};
Listener logic has been refactored out of StreamingProcessor. Each client and server sdk is now responsible for defining their own listeners. They must provide these two functions to deserialize incoming data and then processing that deserialized data. This is further explained [here](https://github.com/launchdarkly/js-core/pull/275/files#r1323687329) and throughout this pr.

2023-09-13 05:16 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.ts
The original StreamingProcessor is moved to this location, however because github doesn't show the diff between main and this branch properly, please refer to my comments [here](https://github.com/launchdarkly/js-core/pull/275/files#r1323670978) for detailed explanation of changes in this file.

2023-09-13 05:16 UTC, yusinto commented on packages/shared/sdk-client/src/configuration/Configuration.ts
> -  public readonly streamReconnectDelay = 1;
I'm making the client and server sdks consistent by calling both `streamInitialReconnectDelay`.

2023-09-13 05:16 UTC, yusinto commented on packages/shared/sdk-server/src/LDClientImpl.ts
> +  private updateProcessor?: subsystem.LDStreamProcessor;
Nullable now because I have removed `NullUpdateProcessor` for reasons  stated [below](https://github.com/launchdarkly/js-core/pull/275/files#r1323785826).

2023-09-13 05:16 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/PollingProcessor.ts
> +    private readonly errorHandler?: PollingErrorHandler,
Since the start function no longer accepts a callback, in the same spirit as the [StreamProcessor](https://github.com/launchdarkly/js-core/pull/275/files#r1323684022) to achieve a cleaner separation of concerns, I have introduced these two new arguments to the PollingProcessor constructor.

2023-09-13 05:22 UTC, yusinto commented on packages/shared/sdk-server/src/integrations/FileDataSourceFactory.ts
> +    errorHandler?: FileDataSourceErrorHandler,
Again note the introduction of separate success and error handlers same [reasons as here](https://github.com/launchdarkly/js-core/pull/275/files#r1323979151).

2023-09-13 23:06 UTC, kinyoklion requested changes

2023-09-14 21:32 UTC, yusinto commented on packages/shared/common/src/api/options/LDClientContext.ts
> +  tags?: { value?: string };
I will rollback `streamInitialReconnectDelay`. Are we able to keep `tags` here? It makes some sense to share that here.

2023-09-14 21:35 UTC, kinyoklion commented on packages/shared/common/src/api/options/LDClientContext.ts
> +  tags?: { value?: string };
I think tags are more generic, so I can see them being here.

2023-09-14 21:43 UTC, yusinto commented on packages/shared/common/src/utils/http.ts
> +  if (wrapperName) {
This change is actually a revert back to main which looks like this:

```tsx
  if (sdkData.wrapperName) {
    headers['x-launchdarkly-wrapper'] = sdkData.wrapperVersion
      ? `${sdkData.wrapperName}/${sdkData.wrapperVersion}`
      : sdkData.wrapperName;
  }
```

There was a bug in the parent branch which includes this header if undefined. So I reverted it back to the way it was in main.

2023-09-14 21:46 UTC, yusinto commented on packages/shared/sdk-server/src/LDClientImpl.ts
> +      process.nextTick(() => this.initSuccess());
No worries I can rollback and use setTimeout like the previous version.

2023-09-15 20:46 UTC, kinyoklion approved these changes

2023-09-15 20:59 UTC, kinyoklion requested changes

2023-09-15 20:59 UTC, kinyoklion commented on packages/shared/common/src/api/subsystem/LDStreamProcessor.ts
> +  start: () => void;
This was part of the public interface, so this is a major version for server SDKs. So, we need to make sure that is coordinated with 9.0

2023-09-15 20:59 UTC, kinyoklion commented on packages/shared/common/src/api/subsystem/LDStreamProcessor.ts
> +  start: () => void;
I re-requested changes on the PR just to make sure we have agreement on this point, then I will re-approve.

2023-09-15 21:10 UTC, yusinto commented on packages/shared/common/src/utils/http.ts
> +  if (wrapperName) {
@kinyoklion are you requesting a correction for me here please?

2023-09-15 21:12 UTC, kinyoklion commented on packages/shared/common/src/utils/http.ts
> +  if (wrapperName) {
No, this is good. Thank you.

2023-09-15 21:14 UTC, yusinto commented on packages/shared/common/src/api/subsystem/LDStreamProcessor.ts
> +  start: () => void;
Are we planning 9.0 release soon?

2023-09-15 21:16 UTC, kinyoklion commented on packages/shared/common/src/api/subsystem/LDStreamProcessor.ts
> +  start: () => void;
Migrations are going to be 9.0 (along with a major bump for each edge SDK.)

2023-09-15 22:32 UTC, kinyoklion approved these changes

2023-09-18 18:46 UTC, yusinto commented on packages/shared/common/src/api/options/LDClientContext.ts
> +  tags?: { value?: string };
streamInitialReconnectDelay removed.

2023-09-18 18:47 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.ts
> +    private readonly streamInitialReconnectDelay = 1,
@kinyoklion I explicitly added streamInitialReconnectDelay here in the constructor, which feels ok given that this is a streamer option. Are you at peace with this please?

2023-09-19 17:56 UTC, merged