chore: implement initial flag fetch
launchdarkly/js-core pull request #294
Opened 2023-10-05 23:30 UTC by yusinto

2023-10-05 23:47 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientDomImpl.ts
> +    }
This is new. This decouples the construction of the ldClient object and the initial poll. The decoupling gives consuming sdks more flexibility how they want initialization to proceed.

2023-10-05 23:53 UTC, yusinto commented on packages/shared/sdk-client/src/api/LDEmitter.ts
> +  private saveListener(name: EventName, originalListener: Function, customListener: Function) {
We need to save both the original listener and the custom listener in order to remove them both correctly from our own internal map and the javascript EventTarget object respectively.

2023-10-05 23:54 UTC, yusinto commented on packages/shared/sdk-client/src/api/LDOptions.ts
> +  withReasons?: boolean;
This is a breaking api change. I'm making this consistent with the server sdks which I think is a good idea.

2023-10-05 23:55 UTC, yusinto commented on packages/shared/sdk-client/src/configuration/Configuration.ts
> +  public static DEFAULT_POLLING = 'https://sdk.launchdarkly.com';
According to this [confluence page](https://launchdarkly.atlassian.net/wiki/spaces/PD/pages/2129461878/Service+endpoints+used+by+SDKs), this is added as part of u2c and so should be the one used. I think either will work.

2023-10-05 23:57 UTC, yusinto commented on packages/shared/sdk-client/src/evaluation/fetchUtils.test.ts
Apologies, this is not done yet, but most of the functionality in this utils class is tested by its consumer, which is fetchFlags. I will get to this soon, in another PR.

2023-10-05 23:57 UTC, yusinto commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
I don't see the need for a dom specific platform for now, so I have deleted this.

2023-10-06 15:43 UTC, kinyoklion requested changes
Ok. We need to determine a different base for you do use, because that base you have chosen has already been merged together with my features. So if you merge there, then you will have the mother of all merge conflicts when you want to eventually merge to main.

`feat/merge-client-and-migrations` contains all of our changes combined, and if what I was going to merge when we are ready to release migrations.

If these changes don't hurt anything, then you could base it on `feat/merge-client-and-migration`, and then it will get merged to main when we release migrations.

If it needs to be held back, then we should make a new `feat/` branch.

I'll look at other things, but I wanted to get the base addressed.

2023-10-06 15:46 UTC, kinyoklion commented on packages/shared/sdk-client/package.json
> +    "jest-fetch-mock": "^3.0.3",
This has not been published in 4 years, which makes me pretty nervous.

2023-10-06 15:50 UTC, kinyoklion commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
I am not ok with not using a platform. Fetch, response, crypto need to go through a platform. It is extra work, but it is important work that makes this code useful and flexible. 

What if we need to do fetch different in node client or electron? What if we need a bun client SDK? What if we need some strange container environment client SDK? What if we need to use filesystem APIs for a custom platform?

The client for DOM is really easy to implement because you just call actual fetch, for instance. Make a client SDK, make it take a platform, now we have set ourselves up to not need polyfills and to have a flexible and extensible base client SDK.

2023-10-06 15:54 UTC, kinyoklion commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
For insance, node 16 is still supported, the client SDK can use the current server platform with a little movement of code. Node 16 only has experimental fetch, so we would need to polyfill. The platform is the most fundamental part of the typescript re-write. Node 16 is also the basis of electron 22, the oldest currently supported electron.

2023-10-06 16:02 UTC, kinyoklion commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
Ah, yeah, platform dom needs to exist, but we should never use it in shared code. I misread this the first time and made a different comment.

sdk-client should work for any possible client platform. So it cannot have knowledge of platform dom.

But platform dom, or something, would need to exist for the browser SDK. We need to hide `fetch` for instance, behind a platform. For me this is an immutable requirement.

For instance when we make the node client SDK, we should hoist the node platform out of server and share it. But it probably should be a different platform than browser. If we support node 16, which is currently an LTS, then we shouldn't use actual browser fetch as it was experimental.

The sdk-server only uses Platform, and then implementors can use more specific platforms.

2023-10-06 16:03 UTC, kinyoklion requested changes

2023-10-06 16:03 UTC, kinyoklion commented on packages/shared/sdk-client/src/evaluation/fetchFlags.ts
> +  const response = await fetch(fetchUrl, fetchOptions);
This needs to come from the platform.

2023-10-06 16:12 UTC, kinyoklion commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
A concrete real example is that electron and node client SDKs should support proxies using the proxy agent. We would not want this code to be in `sdk-client` it would be handled by the platform fetch and not affect browser at all.

2023-10-09 18:17 UTC, yusinto commented
Ok I've merged changes from `feat/merge-client-and-migrations` and changed the PR root. Everything seems to be fine.

2023-10-09 18:33 UTC, yusinto commented on packages/shared/sdk-client/src/platform/PlatformDom.ts
Ok I'll refactor fetch to use Platform.Requests.

2023-10-10 17:59 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientDomImpl.ts
We should remove Dom from the name of this one. Can it just be LDClientImpl?

2023-10-10 18:06 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientDomImpl.ts
Done

2023-10-10 18:13 UTC, kinyoklion approved these changes

2023-10-10 18:23 UTC, merged