fix: Increment version for changing flagValues
launchdarkly/js-core pull request #317
Opened 2023-11-16 23:18 UTC by kinyoklion

2023-11-16 23:23 UTC, kinyoklion commented
@fhawkes If you are setup for development could you give this a try and see if it solves your problems?

2023-11-16 23:36 UTC, kinyoklion commented
There are some additional mismatches in typing that should be addressed. In specifically the FileDataSourceFactory. The old implementation had access to the config directly and was able to access the featureStore. This typing remained, which means it isn't completely correct. We don't have an external type for an update only feature store abstraction, but we 100% should. 

This would be a breaking change, so I am not incorporating it as part of this change. Generally speaking it isn't an interface people implement often unless they are attempting to implement a custom update processor, which is a leaky abstraction we have maintained for backward compatibility.

2023-11-16 23:39 UTC, kinyoklion commented on packages/shared/sdk-server/src/data_sources/FileDataSource.ts
> +        JSON.stringify(parsed.flagValues[key]) !== JSON.stringify(previousInstance?.variations?.[0])
This isn't deterministic. So we may want to do something different here.

2023-11-16 23:41 UTC, kinyoklion commented on packages/shared/sdk-server/src/data_sources/FileDataSource.ts
> +        JSON.stringify(parsed.flagValues[key]) !== JSON.stringify(previousInstance?.variations?.[0])
We don't recommend using FileDataSource in production, so this may be sufficient.

2023-11-20 20:41 UTC, yusinto commented on packages/shared/sdk-server/src/data_sources/FileDataSource.ts
> +    version: version ?? 1,
Is null coalescing needed here? `version` is a number and should not be null or undefined.

```suggestion
    version,
```

2023-11-20 20:49 UTC, yusinto requested changes
One small [comment](https://github.com/launchdarkly/js-core/pull/317/files#r1399726920).

2023-11-21 15:51 UTC, fhawkes commented
> @fhawkes If you are setup for development could you give this a try and see if it solves your problems?

Hey @kinyoklion  I was able to test these changes out and they do solve the issue for us! I'm now seeing flag changes get emitted as expected. Thanks!!

2023-11-27 17:51 UTC, kinyoklion commented on packages/shared/sdk-server/src/data_sources/FileDataSource.ts
> +    version: version ?? 1,
Interesting that linting doesn't catch this. It was leftover from an interim version. Thank you for noticing it.

2023-12-02 15:33 UTC, fhawkes commented
Any movement on this one?

2023-12-04 16:04 UTC, kinyoklion commented on packages/shared/sdk-server/src/data_sources/FileDataSource.ts
> +        JSON.stringify(parsed.flagValues[key]) !== JSON.stringify(previousInstance?.variations?.[0])
I think we can do with this, and then change when we can. Most flags aren't structured as well.

2023-12-04 16:04 UTC, kinyoklion commented
Hey @fhawkes,

No movement. I will see if I can get to it soon.

Thank you,
Ryan

2023-12-04 17:50 UTC, yusinto approved these changes

2023-12-04 21:15 UTC, merged