chore: Exclude js-eventsource logic from StreamingProcessor
launchdarkly/js-core pull request #320
Opened 2023-11-23 00:05 UTC by yusinto

This PR modifies the StreamingProcessor so it is compatible with  any EventSource implementation, not just js-eventsource. The react native sdk has its own event source implementation, so this is necessary. This is also a precursor for future attempts to replace the js-eventsource completely.

2023-11-23 00:06 UTC, yusinto commented on packages/shared/common/src/api/platform/EventSource.ts
>    onretrying: ((e: { delayMillis: number }) => void) | undefined;
callout: I understand this is a public api so this is a breaking change(?)

2023-11-23 00:07 UTC, yusinto commented on packages/shared/common/src/api/platform/Requests.ts
> +  createEventSource(url: string, eventSourceInitDict?: EventSourceInitDict | any): EventSource;
Relax es creation options so other implementations can work.

2023-11-23 00:10 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.ts
> -    this.eventSource = eventSource;
The logic for creating an EventSource now the responsibility of the consumer in order to keep StreamingProcessor as compatible as possible.

2023-11-23 00:21 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.ts
> -      // The work is done by `errorFilter`.
I checked [js-eventsource](https://github.com/launchdarkly/js-eventsource/blob/44e77f3f6debb322d5233fe2d3f9484cd1ded55e/lib/eventsource.js#L157) and it uses `errorFilter` for two purposes: to handle errors and to determine if a retry should be made. With this change, `errorFilter`'s only responsibility is the latter i.e. determining if a retry should be made. 

The error handling will be done by `logAndHandleErrors`. The net effect is there
s no change in functionality because `js-eventsource` emits the `error` event after invoking `errorFilter`.

2023-11-23 00:23 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.ts
> -    };
`errorFilter` is now declared as part of `createEventSource`.  See my comments [below](https://github.com/launchdarkly/js-core/pull/320/files#r1402818569).

2023-11-23 00:25 UTC, yusinto commented on packages/shared/sdk-server/src/LDClientImpl.ts
> +    };
Creates js-eventsource. `errorFilter` is now only responsible for determining if retries should be made.

2023-11-23 07:46 UTC, yusinto commented on packages/shared/common/src/internal/stream/StreamingProcessor.test.ts
> -  });
Moved to LDClientImpl.test.ts because `createEventSource` logic is part of LDClientImpl now.

2023-11-27 16:52 UTC, kinyoklion commented
So, other SDKs have traditionally already had other event sources. This API is abstract enough to work with the polyfill or the browser, for instance. It does require writing some small amount of glue code for compatibility with the interface.

Is there some specific reason you could not encapsulate it? I don't see why the streaming level would need access to implementation detail related to this event source.

As we just did two major versions of the node SDK I am against further changes to the public interface.

2023-11-27 16:54 UTC, kinyoklion commented on packages/shared/common/src/api/platform/Requests.ts
> +  createEventSource(url: string, eventSourceInitDict?: EventSourceInitDict | any): EventSource;
What is the problem with this? This provides a stable way to make different event sources. It isn't intended to attack to the specific event source. Allowing any removes the value of having some common abstract settings.

All event sources may not need to use them, but we should have a superset of data. For instance the browser event source wouldn't use anything but the error filter (any it may only result in reporting.)

2023-11-27 16:54 UTC, kinyoklion commented on packages/shared/common/src/api/platform/Requests.ts
> +export interface HttpErrorResponse {
This is probably good/fine.

2023-11-27 17:14 UTC, kinyoklion requested changes
I need to understand why these changes are needed. I don't see anything that would make or break compatibility with any event source that we may want to implement.

I think the changes themselves are improvements.

2023-11-27 19:02 UTC, kinyoklion commented on packages/shared/common/src/utils/http.ts
> +  return !(err.status && !isHttpRecoverable(err.status));
(And theoretically status is not optional based on typing, but is based on reality.)

2023-11-27 19:03 UTC, kinyoklion commented on packages/shared/common/src/api/platform/EventSource.ts
> -  errorFilter: (err: { status: number; message: string }) => boolean;
Theoretically breaking, but not really a breaking change being as it could have actually been undefined already. :shrug:

2023-11-27 21:17 UTC, yusinto commented on packages/shared/common/src/api/platform/EventSource.ts
> -  errorFilter: (err: { status: number; message: string }) => boolean;
Ok I've made status optional and made the err argument optional as well for backwards compat.

2023-11-27 21:24 UTC, kinyoklion commented on packages/shared/common/src/api/platform/Requests.ts
> +  createEventSource(url: string, eventSourceInitDict?: EventSourceInitDict | any): EventSource;
@yusinto This is the one I was talking about. We should have standard parameteters and the event source decides what to do with them. Versus `any`.

2023-11-27 23:31 UTC, kinyoklion approved these changes

2023-11-28 00:43 UTC, merged