chore: rn sdk use localstorage for bootstrapping
launchdarkly/js-core pull request #326
Opened 2023-12-18 21:51 UTC by yusinto

2023-12-18 21:53 UTC, yusinto commented on packages/sdk/react-native/package.json
> +    "@react-native-async-storage/async-storage": "^1.21.0",
We need this now since AsyncStorage is removed in 0.73.

2023-12-18 21:54 UTC, yusinto commented on packages/sdk/react-native/src/hooks/useLDDataSourceStatus.ts
I used this for debugging but now no longer required.

2023-12-18 21:57 UTC, yusinto commented on packages/shared/common/src/utils/fast-deep-equal/index.ts
I add this locally because there are typescript es6 issues with the original package from npm. I tried my best to solve that but could not get it to work in the timebox. I think it's ok to have a copy of this so we can share it and be independent.

2023-12-18 21:59 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +    }
Callout here to highlight the new bootstrap from storage implementation.

2023-12-18 22:01 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +      processJson: async (dataJson: Flags) => {
Callout here to highlight the new synchronization logic between storage and streamer.

2023-12-18 22:02 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          delete this.flags[dataJson.key];
I perform a hard delete here but the legacy js common performs a soft-delete (tombstoning). I don't see the need for soft-deleting. Is this ok?

2023-12-18 22:05 UTC, yusinto commented on packages/sdk/react-native/example/package.json
> +    "@react-native-async-storage/async-storage": "1.18.2",
I had to add this as a dep of the example app to get auto-linking to work. I'm not sure if this is the best way?

2023-12-18 23:26 UTC, yusinto commented on packages/sdk/react-native/example/package.json
> +    "@react-native-async-storage/async-storage": "1.18.2",
Additionally, [expo 49 only supports rn 0.72](https://docs.expo.dev/versions/latest/#each-expo-sdk-version-depends-on-a-react-native-version). Expo 50 will work with 0.73 and it's in beta with full release coming in about month.

2023-12-19 00:06 UTC, yusinto commented on packages/sdk/react-native/src/ReactNativeLDClient.ts
> +        level: 'debug',
I intentionally left this as `debug` for the alpha.

2023-12-19 16:57 UTC, kinyoklion commented on packages/shared/sdk-client/src/api/LDEmitter.ts
> -export type EventName = 'connecting' | 'ready' | 'error' | 'change';
Are you keeping a list of breaking changes for when we do a js-client release? Things like this seem like they could be easy to slip through the cracks.

2023-12-19 17:12 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +      processJson: async (dataJson: Flags) => {
I don't have a good picture of what the external picture is for using the SDK.

When do I first know the SDK is ready?
When do I know that a specific identify is complete?

Can I split those two things?
Can I use async as well as callbacks?

(This looks like it emits ready any time we get a put, but if we have bootrap we should already be ready. Or if you got more than 1 put message, not something we currently do, but I don't think we specifically disallow it.)

2023-12-19 18:03 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +      processJson: async (dataJson: Flags) => {
Reconnecting to a stream is probably in this case as well.

2023-12-19 18:10 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +      processJson: async (dataJson: Flags) => {
> When do I first know the SDK is ready?

It's like you said. `ready` is emitted at 2 places: 

* bootstrap from [storage is complete](https://github.com/launchdarkly/js-core/blob/87d09ba00cd8aa15ea605cd7d479128b6c307e67/packages/shared/sdk-client/src/LDClientImpl.ts#L266)
* if no bootstrap when the [put is complete](https://github.com/launchdarkly/js-core/blob/87d09ba00cd8aa15ea605cd7d479128b6c307e67/packages/shared/sdk-client/src/LDClientImpl.ts#L151).

> When do I know that a specific identify is complete?

There are two ways:
* awaiting `identify` like [this](https://github.com/launchdarkly/js-core/blob/80cc003407bdbd4aa46b9a1d0043dc8528f6adbe/packages/sdk/react-native/example/src/welcome.tsx#L14)
* listening to the `ready` event which includes the context identified as a callback param.

> Can I split those two things?

Can you please clarify what you want to split? In the clean-slate start-from-scratch scenario, you call `identify` and either await that or listen to `ready` for completion.

> Can I use async as well as callbacks?

`identify` is async only. `ready` is an event so it needs an event listener with a callback.

2023-12-19 18:17 UTC, yusinto commented on packages/shared/sdk-client/src/api/LDEmitter.ts
> -export type EventName = 'connecting' | 'ready' | 'error' | 'change';
I plan to submit a follow up PR to update all comments, readme and docs including breaking changes. I want to get the code reviewed asap first. The `connecting` event is updated to `initializing` though to follow @cwaldren-ld 's [spec](https://github.com/launchdarkly/sdk-specs/tree/cw/sc-215574/persistent-spec/specs/SDKC-SDK-core/DS-data-system#141-overview).

2023-12-20 21:59 UTC, kinyoklion commented on packages/sdk/react-native/README.md
> +# ios
The readme in the example seems to have instructions, but these instructions here have pre-requisites, like setting the mobile key, which makes this misleading.

2023-12-20 22:10 UTC, kinyoklion commented on packages/shared/mocks/src/streamingProcessor.ts
>            process.nextTick(() => listeners.get('put')?.processJson(putResponseJson));
I wonder if these were a `Promise.resolve` or `setTimeout` with 0 if you wouldn't need to process the ticks? (I know this is a test, but `process.nextTick` always alarms me for a moment, being as it isn't portable.

2023-12-20 22:13 UTC, kinyoklion requested changes

2023-12-20 22:13 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          delete this.flags[dataJson.key];
Technically yes, our algorithm currently requires a tombstone. It may not in the future. If you get a delete and a patch you could get them in the wrong order. Without the tombstone you wouldn't detect it.

Imagine flag A has a value of "a" in version 1.
We patch flag A to "b" in version 2.
We delete flag A in version 3.

We get version 1 on a put, we get version 3 on a delete, and then we get version 2.

With a tombstone we know we got the update out of order. Without the tombstone we do not, so the flag will come back into existence.

2023-12-20 23:13 UTC, yusinto commented on packages/shared/mocks/src/streamingProcessor.ts
>            process.nextTick(() => listeners.get('put')?.processJson(putResponseJson));
I will attempt to replace nextTick with what you suggested and respond.

2023-12-20 23:14 UTC, yusinto commented on packages/sdk/react-native/README.md
> +# ios
Good point. I will improve this to be clearer and independent.

2023-12-20 23:14 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          delete this.flags[dataJson.key];
Thanks for the clarification. I will do this.

2023-12-21 23:48 UTC, kinyoklion commented on packages/sdk/react-native/README.md
>  ```shell
Need to add `MOBILE_KEY` to the `.env` as well.

2023-12-22 00:10 UTC, yusinto commented on packages/sdk/react-native/README.md
>  ```shell
Done.

2023-12-22 00:12 UTC, yusinto commented on packages/shared/mocks/src/streamingProcessor.ts
> +          setTimeout(() => {
Using `setTimeout` actually resolves the "weird" async issue in one of the storage tests related to ticks. @kinyoklion thanks for the suggestion!

2023-12-22 05:48 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          delete this.flags[dataJson.key];
Done in #328

2023-12-22 18:18 UTC, kinyoklion approved these changes

2023-12-22 18:18 UTC, merged