fix: Implement anonymous context processing
launchdarkly/js-core pull request #350
Opened 2024-01-18 20:00 UTC by yusinto

2024-01-18 20:02 UTC, yusinto commented on packages/shared/sdk-client/src/utils/calculateFlagChanges.ts
This was in `index.ts` but I moved it now to its own explicit file.

2024-01-18 20:06 UTC, yusinto commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> +export const ns = (s: string) => `LaunchDarkly_AnonKeys_${s}`;
I'm using `LaunchDarkly_AnonKeys_` which is different from the existing js common. We may have to worry about migrating existing keys. Although for the react native sdk, since it's a brand new sdk using a new storage package, migration maybe difficult if not impossible.

2024-01-18 20:09 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.test.ts
> +    const carContext: LDContext = { kind: 'car', anonymous: true, key: '' };
Even anonymous, `key` is a required field so it has to be set to an empty string. I think this is fine, but calling this out for concerns/discussion.

2024-01-18 21:19 UTC, kinyoklion commented on packages/shared/common/src/Context.ts
> +export function isSingleKind(context: LDContext): context is LDSingleKindContext {
I have serious reservations about exporting these functions. We don't want them exported from the final package and becoming part of the stable API of all of the packages.

2024-01-18 21:21 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.test.ts
> +    const carContext: LDContext = { kind: 'car', anonymous: true, key: '' };
If you are ok with that requirement. I was originally planning on exporting a different type from client SDKs that did not require a key. Then internal to the client implementation decorate it (generate keys, verify anonymous is set)  and create a `Context`.

Because I think that the pattern we had before, where you don't include a key and that makes the context anonymous is very intuitive.

2024-01-18 21:23 UTC, kinyoklion commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> +export const ns = (s: string) => `LaunchDarkly_AnonKeys_${s}`;
Could we name this function `namespaced` or something more explicit. I read the later code before this and was like what is an `nsKind`?

2024-01-18 23:35 UTC, yusinto commented on packages/shared/common/src/Context.ts
> +export function isSingleKind(context: LDContext): context is LDSingleKindContext {
Will you be open to exporting these from `internal` please? They are useful internally and the common sdks can re-use them for internal logic.

2024-01-18 23:44 UTC, kinyoklion commented on packages/shared/common/src/Context.ts
> +export function isSingleKind(context: LDContext): context is LDSingleKindContext {
I am ok with them being in internal.

I am really concerned about them being useful outside these two cases. They really are not supposed to be.

We are provided an `LDContext` and we then validate that into a `Context`. Once we have a `Context` these functions are not useful. 

So, if we are careful to try not to use LDContext, aside from adding keys to it and then constructing a context, then that is probably fine.

2024-01-18 23:47 UTC, yusinto commented on packages/shared/common/src/Context.ts
> +export function isSingleKind(context: LDContext): context is LDSingleKindContext {
Agreed. I'll add comments in this file reflecting what you said.

2024-01-19 00:11 UTC, yusinto commented on packages/shared/sdk-client/src/LDClientImpl.test.ts
> +    const carContext: LDContext = { kind: 'car', anonymous: true, key: '' };
I'm fine with this for now.

2024-01-19 16:43 UTC, kinyoklion requested changes

2024-01-19 16:43 UTC, kinyoklion commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> +const ensureKey = async (c: LDContext, platform: Platform) => {
I think I missed that we are modifying the context which is provided, versus modifying a copy. Typically we would never directly change things which are provided to the SDK. 

We could either always clone, which is probably fine because identify isn't a high frequency situation.

Or only clone when we determine that we need to.

2024-01-19 18:17 UTC, yusinto commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> +const ensureKey = async (c: LDContext, platform: Platform) => {
Ok I'll clone and return the new object from ensureKey.

2024-01-19 18:45 UTC, yusinto commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> +const ensureKey = async (c: LDContext, platform: Platform) => {
Done.

2024-01-19 18:54 UTC, kinyoklion approved these changes

2024-01-19 18:54 UTC, merged