chore: Support react-native auto env
launchdarkly/js-core pull request #354
Opened 2024-01-24 20:52 UTC by yusinto

Big PR for react native because:

- We are adding auto env support.
- It needs Platform.Crypto to be implemented.
- Mocks and tests must be modified.

2024-01-24 21:24 UTC, yusinto commented on packages/sdk/react-native/src/fromExternal/js-sha256/index.js
This is a pure js implementation [js-sha256]{@link https://github.com/emn178/js-sha256}. I'm cloning this into our repo for full control. I deleted node-js related code from this. I also grouped react-native-sse and this sha library into a new dir `fromExternal`.

2024-01-24 21:26 UTC, yusinto commented on packages/sdk/react-native/src/platform/autoEnv.ts
> +  versionName: '',
I'm still unsure how to populate these without installing the heavyweight react-native-device-info or having native dependencies. We may have to document this to request customers to set the application tags for these to be correctly populated.

2024-01-24 21:28 UTC, yusinto commented on packages/sdk/react-native/src/polyfills/uuid.ts
Moved to platform/crypto for posterity.

2024-01-24 21:29 UTC, yusinto commented on packages/sdk/react-native/src/platform/crypto/PlatformHasher.ts
> +        return base64FromByteArray(new Uint8Array(this.hasher.arrayBuffer()));
The js-sha256 library supports hex output but not base64. I'm doing it manually here.

2024-01-24 21:32 UTC, yusinto commented on packages/shared/mocks/src/platform.ts
> +    crypto: setupCrypto(),
I encountered mock issues where mock resets don't work with static exports in deep nested mocks. Therefore I have to make these changes and introduce a flagfall test setup step for the mocks package.

2024-01-24 21:33 UTC, yusinto commented on packages/shared/mocks/src/setupMocks.ts
This needs to be run beforeEach test for basicPlatform mocks to be setup and initialized correctly.

2024-01-24 21:34 UTC, yusinto commented on packages/shared/sdk-client/jest-setupFilesAfterEnv.ts
This file seems unused and its removal does not break anything.

2024-01-24 21:36 UTC, yusinto commented on packages/shared/sdk-client/src/utils/ensureKey.ts
> -};
These are moved to a separate file `getOrGenerateKey.ts`.

2024-01-24 21:37 UTC, yusinto commented on packages/shared/sdk-client/src/utils/addAutoEnv.ts
> +};
Converting a single kind to multi kind. Is this logic correct and sufficient enough?

2024-01-24 21:41 UTC, yusinto commented on packages/shared/sdk-server-edge/jest.config.json
All remaining changes below this comment are related to the mocks api being changed due to basicPlatform needing to be setup on beforeEach.

2024-01-24 21:42 UTC, yusinto commented on packages/shared/sdk-client/src/utils/addAutoEnv.ts
This is the main auto env logic.

2024-01-24 21:57 UTC, yusinto commented on packages/shared/sdk-client/src/utils/addAutoEnv.ts
> +  }
Call out we are not supporting LDUser for auto env.

2024-01-24 21:59 UTC, yusinto commented on packages/shared/sdk-client/src/utils/addAutoEnv.ts
> +    config.application?.version || ldApplication.version || version || wrapperVersion;
I follow the [spec logic](https://github.com/launchdarkly/sdk-specs/blob/main/specs/AUTOENVATTR-automatic-environment-attributes/README.md#requirement-1252) here, but the spec does not specify how application `name` should be populated. Is this acceptable?

2024-01-24 23:32 UTC, kinyoklion commented on packages/sdk/react-native/src/platform/autoEnv.ts
> +  manufacturer: Platform.select({
Pinging @tanderson-ld on these values. 

@yusinto Do you have the JSON of one of the contexts populated?

2024-01-24 23:32 UTC, kinyoklion commented on packages/sdk/react-native/src/platform/autoEnv.ts
> +  key: '',
I assume this gets populated later, maybe a comment to explain?

2024-01-24 23:32 UTC, kinyoklion commented on packages/sdk/react-native/src/platform/autoEnv.ts
> +  versionName: '',
If we cannot collect, then we will want to exclude them when they are not populated.

2024-01-24 23:37 UTC, kinyoklion commented on packages/shared/mocks/src/platform.ts
> +        name: 'iOS',
Why this change? It is good for this data to not look like real runtime data.

2024-01-24 23:40 UTC, kinyoklion commented on packages/shared/common/src/api/platform/AutoEnv.ts
So, it would be nice if, for instance the stuff in `common` was just 1 PR against a feature branch. Nice encapsulated change that is easy to follow in isolation.

2024-01-24 23:44 UTC, kinyoklion requested changes
This PR contains changes that require common release, for instance, so it cannot be a chore. 

I think we should break this PR down into some units with some associated conventional commits that will make them digestable.

`feat: Implement common support for auto environment attributes.`
`feat: Implement common client side support for auto environment attributes.`
`feat: React-native support for auto-env attributes.`

Each PR affecting the correct components to produce the generally correct changlog history.

If there are some sweeping changes for mocks or jest config, then those could be done in a chore.

2024-01-24 23:55 UTC, yusinto commented on packages/sdk/react-native/src/platform/autoEnv.ts
> +  manufacturer: Platform.select({
This is from the ios simulator:

```json
{
  "kind": "multi",
  "user": {
    "key": "test-user"
  },
  "ld_application": {
    "key": "/zFu3yVDTWyKZ6vG+ssjgcM9uSTmTpD2u/QTEy2FFVY=",
    "envAttributesVersion": "1.0",
    "id": "@launchdarkly/react-native-client-sdk",
    "name": "@launchdarkly/react-native-client-sdk",
    "version": "0.1.5",
    "versionName": "",
    "locale": "en_US"
  },
  "ld_device": {
    "key": "21105df8-0236-4ef5-9721-f94f68424560",
    "envAttributesVersion": "1.0",
    "manufacturer": "apple",
    "os": {
      "family": "apple",
      "name": "ios",
      "version": "17.2"
    }
  }
}
```

2024-01-24 23:59 UTC, yusinto commented on packages/shared/mocks/src/platform.ts
> +        name: 'iOS',
No reason. I can revert all good.

2024-01-25 00:01 UTC, kinyoklion commented
Overall I think things are looking good. I do think we need to break it up though and apply it in smaller bits that can be released and have associated change notes.

2024-01-25 00:08 UTC, yusinto commented
> we need to break it up

I'm on it. Thank you for your feedback. Apologies for this monster pr.

2024-02-01 20:48 UTC, yusinto commented
Closing this because it has been broken up and superseded by #356  #357 #358.

2024-02-01 20:48 UTC, closed without merging