fix: Stream retry failure due to previous open connection.
launchdarkly/js-core pull request #409
Opened 2024-03-26 22:49 UTC by yusinto

2024-03-26 22:51 UTC, yusinto commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +  initialRetryDelayMillis: 5000,
Increasing this on a mobile device seems like a good idea so as to not drain power.

2024-03-26 22:51 UTC, yusinto commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +      this.close();
`react-native` has its own implementation of `XMLHttpRequest` which throws an error if a previous connection is still `open` and you try to re-open it. Here we are closing the connection first to solve that error.

2024-03-26 22:51 UTC, yusinto commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +        this.logger?.debug(`[EventSource][dispatch][ERROR]: ${JSON.stringify(data)}`);
This is much needed for debugging.

2024-03-26 22:58 UTC, kinyoklion commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +  initialRetryDelayMillis: 5000,
I would rather change this independently, unless it contributes to the fix. Because the initial retry is 1 second, when streaming, among the SDKs.

2024-03-26 22:59 UTC, kinyoklion approved these changes

2024-03-26 22:59 UTC, kinyoklion requested changes
Tests are failing.

2024-03-27 15:48 UTC, kinyoklion approved these changes

2024-03-27 15:48 UTC, merged