fix: Improved retry reset logic to wait before resetting.
launchdarkly/js-core pull request #427
Opened 2024-04-08 20:20 UTC by yusinto

2024-04-08 20:40 UTC, kinyoklion requested changes

2024-04-08 20:40 UTC, kinyoklion commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +  private resetRetryCount() {
This implements a different style of reset than other SDKs.

If you connect then it will reset the retry count after 1 minute regardless how many other problems happen later. Also it can have multiple concurrent timers running.

The logic would typically not use a timer, but it could be made to use a timer by:
Cancel the timer if a timer already exists and start a new timer.
Cancel the timer if there is an error.
(You shouldn't have to clear the timer in the handler, because it should have already ran.)

Generally it has been done with a timestamp. 

Set a timestamp when you connect.

When you have an error check to see if there is a timestamp and it is more more than 1 minute ago. Clear the timestamp and reset the retry count.

2024-04-08 20:42 UTC, kinyoklion commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +  private resetRetryCount() {
I think we need to at least clear the timeout on an error.

2024-04-09 17:54 UTC, yusinto commented on packages/sdk/react-native/src/fromExternal/react-native-sse/EventSource.ts
> +  private resetRetryCount() {
No worries I'll rewrite this to use timestamps as you suggest.

2024-04-09 20:35 UTC, kinyoklion approved these changes

2024-04-09 20:42 UTC, kinyoklion requested changes
Un-approving for test failure.

2024-04-11 19:57 UTC, yusinto commented
I detected some scenarios which are not being retried while fixing this. I'm investigating and fixing those, I'll close this PR for now in favor of that.

2024-04-11 19:57 UTC, closed without merging