feat: Allow waiting for the network response on identify.
launchdarkly/js-core pull request #548
Opened 2024-08-16 22:26 UTC by kinyoklion

2024-08-16 22:27 UTC, kinyoklion commented on packages/shared/mocks/src/crypto.ts
> -// eslint-disable-next-line import/no-mutable-exports
Forgot to remove this piece of global data in the test updates.

2024-08-16 22:27 UTC, kinyoklion commented on packages/shared/mocks/src/hasher.ts
This file was redundant.

2024-08-16 22:27 UTC, kinyoklion commented on packages/shared/mocks/src/streamingProcessor.ts
> +  let initTimeoutHandle: any;
The simulated stream needs to be able to cancel its timers or it will run after tests are expected to end.

2024-08-16 22:28 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.test.ts
> +  let ldc: LDClientImpl;
Decreasing the scope of these to the fixture.

2024-08-19 16:42 UTC, tanderson-ld requested changes

2024-08-19 16:42 UTC, tanderson-ld commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          'Offline identify - no cached flags, using defaults or already loaded flags.',
```suggestion
          'Identify - Currently offline with no cached flags for provided context.  Maintaining current flags. This may result in default flag evaluations if no flags have been loaded before.'
```

Is the trailing comma intentional?

2024-08-19 16:42 UTC, tanderson-ld commented on packages/shared/sdk-client/src/api/LDIdentifyOptions.ts
> +   * It the client is set to offline mode, then this option is ignored.
```suggestion
   * If the client is set to offline mode, then this option is ignored.
```

2024-08-19 17:38 UTC, kinyoklion commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +          'Offline identify - no cached flags, using defaults or already loaded flags.',
Our linting requires training coma for parameters that are not on one line. The linter also forces this line to be wrapped as such.

2024-08-19 21:02 UTC, tanderson-ld approved these changes

2024-08-19 21:06 UTC, merged

2024-08-21 11:54 UTC, Bardiamist commented on packages/shared/sdk-client/src/api/LDIdentifyOptions.ts
>    timeout: number;
@kinyoklion `timeout` should be optional then

2024-08-21 15:21 UTC, kinyoklion commented on packages/shared/sdk-client/src/api/LDIdentifyOptions.ts
>    timeout: number;
Unfortunately timeout was already implemented as non-optional. That said it defaults to 5, so setting it to 5 is equal to not providing it.

2024-08-21 15:29 UTC, kinyoklion commented on packages/shared/sdk-client/src/api/LDIdentifyOptions.ts
>    timeout: number;
We will consider it. 

There are advantages to having it non-optional and some SDKs require it with every call identify. Which makes it more obvious that the operation can timeout. We document it, but people are still often surprised that it times out.