Ta/sc 251674/streaming report
launchdarkly/js-core pull request #575
Opened 2024-09-09 19:53 UTC by tanderson-ld

**Requirements**

- [ ] I have added test coverage for new or changed functionality
Still adding tests.
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

251674

**Describe the solution you've provided**

- Added useReport to LDOptions.
- Piped through client to `StreamingProcessor` constructor.
- Cloned `StreamingProcessor` and associated tests from common-internal to sdk-client.  Refactored it to support taking in a `StreamingDataSourceConfig` to narrow provided dependencies instead of ClientContext which contained many concerns.  `StreamingProcessor` now uses a paths provider to form URI and internally decides where to put the serialized context (url vs body).
- Refactored LDClientImpl tests to not use MockStreamingProcessor to reduce global mock usage.

**Describe alternatives you've considered**

Initially tried making changes in common-internal, but the existence of the client context in the URL or body for client situations made that not ideal.

2024-09-09 19:56 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
This is a clone of common/internal/stream/StreamingProcessor with changes to the constructor and start to support using REPORT.

2024-09-09 19:56 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
> +  }
Main changes are in this constructor.

2024-09-09 19:57 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
> +      ...(this.dataSourceConfig.useReport && { method: 'REPORT', body: this.plainContextString }),
This line is responsible for the usage of REPORT.

2024-09-09 20:03 UTC, tanderson-ld commented on packages/shared/sdk-client/__tests__/LDClientImpl.storage.test.ts
Most of the changes in these test files relate to eliminating the usage of setupMockStreamingProcessor

2024-09-09 20:27 UTC, tanderson-ld commented on packages/shared/sdk-client/src/configuration/Configuration.ts
> +  public readonly withReasons: boolean = false;
Please doublecheck this is a fine change.  It does seem to change the typing, but I think these should be boolean.

2024-09-09 20:29 UTC, tanderson-ld commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +        initialRetryDelayMillis: 1000,
Changed to take in millis instead of whole seconds for better resolution.  This 1 second constant was defined before as a default parameter.

2024-09-10 15:40 UTC, tanderson-ld commented on packages/shared/sdk-client/src/LDClientImpl.ts
> +        initialRetryDelayMillis: 1000,
It looks like this wasn't piped from the config.  Updated to use the config.  Please verify the `streamInitialReconnectDelay` is the correct option.

2024-09-10 16:02 UTC, tanderson-ld commented
Updated from using `this.clientContext.basicConfiguration.tags` (optional) to using `this.config.tags` (non-optional).  Need to double check application tags handling is proper.

2024-09-11 14:38 UTC, tanderson-ld commented
Need to throw exception when useReport is true but platform does not support custom http methods.  Also need to create ticket for adding better handling.

2024-09-12 20:28 UTC, tanderson-ld commented
> Need to throw exception when useReport is true but platform does not support custom http methods. Also need to create ticket for adding better handling.

Done, added logging instead of exception.

2024-09-13 21:42 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
> +    }
For reviewers: Main changes are in this constructor and start.

2024-09-16 15:00 UTC, tanderson-ld commented
> Updated LDClientImpl.ts from using `this.clientContext.basicConfiguration.tags` (optional) to using `this.config.tags` (non-optional). Need to double check application tags handling is proper.

Verified application tag is being handled correctly.

2024-09-16 17:10 UTC, kinyoklion requested changes

2024-09-17 15:22 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
Created SDK-156

2024-09-17 15:59 UTC, tanderson-ld commented on packages/shared/sdk-client/src/streaming/StreamingProcessor.ts
> +      logger?.warn(
Updated.

2024-09-17 16:19 UTC, tanderson-ld commented on packages/sdk/browser/src/BrowserClient.ts
> +      pathGet(encoding: Encoding, _credential: string, _plainContextString: string): string {
Done.

2024-09-17 16:57 UTC, tanderson-ld commented on packages/sdk/react-native/package.json
> +    "android": "yarn && yarn ./example && yarn build && (cd example/ && yarn android)",
After more discussion in slack, removed commands related to the example.

2024-09-18 15:42 UTC, kinyoklion approved these changes

2024-09-18 15:49 UTC, merged