AI Tracking Updates
launchdarkly/js-core pull request #634
Opened 2024-10-25 16:48 UTC by InTheCloudDan

Merge AI Tracking updates into overall model config branch.

* Added new methods for `durationOf` `trackOpenAI` and `trackBedrockConverse`.
* Fixed NPM scripts
* Removed extraneous console logs

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

Provide links to any issues in this repository or elsewhere relating to this pull request.

**Describe the solution you've provided**

Provide a clear and concise description of what you expect to happen.

**Describe alternatives you've considered**

Provide a clear and concise description of any alternative solutions or features you've considered.

**Additional context**

Add any other context about the pull request here.

2024-10-28 15:22 UTC, kinyoklion commented on packages/sdk/ai/src/LDAIConfigTracker.ts
>  export class LDAIConfigTracker {
I need to check the base PR, but this should be implementing an interface, and the interface is what the customer is aware of.

2024-10-28 15:23 UTC, kinyoklion commented on packages/sdk/ai/src/LDAIConfigTracker.ts
> +  async trackDurationOf(func: Function, ...args: any[]): Promise<any> {
The func signature probably needs to indicate it is async.

2024-10-28 15:31 UTC, kinyoklion requested changes

2024-10-28 15:31 UTC, kinyoklion commented on packages/sdk/ai/src/LDAIConfigTracker.ts
> +  async trackBedrockConverse(res: any): Promise<any> {
Can we inline a type here that has things we expect?

```
{'$metadata'?: {httpStatusCode: number}, metrics: {latencyMs: number}, usage: ???}};
```

2024-10-28 15:31 UTC, kinyoklion commented on packages/sdk/ai/src/api/metrics/BedrockTokenUsage.ts
> +  constructor(data: any) {
A type of some kind would be good here. Typescript is structural, so it just needs to have the stuff that we need to understand.

2024-10-28 15:31 UTC, kinyoklion commented on packages/sdk/ai/src/api/metrics/OpenAITokenUsage.ts
> +  constructor(data: any) {
Same as others.

2024-10-28 15:31 UTC, kinyoklion commented on packages/sdk/ai/src/api/metrics/OpenAITokenUsage.ts
> +  constructor(data: any) {
I am going to stop tagging now. But generally we want to avoid any, unless we really need to. Here we know several fields, so we should be able to say we need those.

2024-10-28 15:31 UTC, kinyoklion commented on packages/sdk/ai/src/index.ts
> +        detail.value['_ldMeta'].variationId,
Why not use dot notation here? detail.value._ldMeta should work fine. Though other things would still make the line potentially unhappy.

2024-10-31 19:13 UTC, cwaldren-ld commented on packages/sdk/ai/package.json
>    "main": "dist/index.js",
I think the package name should follow our normal conventions, likely `@launchdarkly/node-server-sdk-ai`. I can see this might require some discussion.

2024-11-01 17:17 UTC, closed without merging