feat: Adds StreamingProcessor for FDv2 to sdk-server package.
launchdarkly/js-core pull request #707
Opened 2024-12-09 19:24 UTC by tanderson-ld

**Requirements**

- [ ] I have added test coverage for new or changed functionality
TODO

- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Related issues**

TODO

**Describe the solution you've provided**

TODO

**Describe alternatives you've considered**

TODO

2024-12-10 19:18 UTC, tanderson-ld commented on packages/shared/common/src/internal/fdv2/payloadReader.ts
> +export class PayloadReader {
TODO: commenting

2024-12-12 20:39 UTC, kinyoklion requested changes

2024-12-18 20:07 UTC, tanderson-ld commented on packages/shared/common/__tests__/internal/fdv2/PayloadReader.test.ts
> +class MockEventStreamm implements EventStream {
Done

2024-12-18 20:07 UTC, tanderson-ld commented on packages/shared/common/__tests__/internal/fdv2/PayloadReader.test.ts
> +    [event: EventName]: EventListener;
Done

2024-12-18 20:07 UTC, tanderson-ld commented on packages/shared/common/src/internal/fdv2/payloadReader.ts
> +    if ((event?.data?.payloads.length ?? 0) <= 0) {
Done

2024-12-18 20:08 UTC, tanderson-ld commented on packages/shared/common/src/internal/fdv2/payloadReader.ts
> +  listeners: PayloadListener[] = [];
Good call.  Done.

2024-12-20 19:03 UTC, kinyoklion approved these changes

2024-12-23 21:45 UTC, merged