feat: vercel edge sdk
launchdarkly/js-core pull request #77
Opened 2023-04-12 14:58 UTC by monsagri

**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [ ] I have followed the repository's [pull request submission guidelines](../blob/main/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Describe the solution you've provided**

DRAFT
[sc-194414]

This adds an Edge SDK for Vercel to be used with Vercel Edge Configs. 
I still need to add some testing, but things work as expected when I link the package to a vercel project running locally.

2023-04-13 14:14 UTC, monsagri commented on packages/sdk/vercel/src/createLdClient/createOptions.ts
> +  sendEvents: false,
Leaving this for a follow up PR as it's a nice to have

2023-04-13 14:15 UTC, monsagri commented on packages/sdk/vercel/src/platform/crypto/index.ts
> +    return uuidv4();
Feel like I'm doing something wrong here, see todo above

2023-04-13 16:00 UTC, kinyoklion commented on packages/sdk/vercel/src/platform/crypto/index.ts
> +    return uuidv4();
Does crypto.randomUUID work in vercel?

https://vercel.com/templates/next.js/edge-functions-crypto

2023-04-13 16:02 UTC, kinyoklion commented
We figured we would need a shared folder for some potentially common edge provider items, but it is hard to say for sure until you make 2. :-)

2023-04-13 16:06 UTC, kinyoklion commented on packages/sdk/vercel/src/createLdClient/createFeatureStore.ts
> +  const store: LDFeatureStore = {
Could you implement the feature store as a class? `class VercelFeatureStore implements LDFeatureStore`?

2023-04-13 16:09 UTC, kinyoklion commented on packages/sdk/vercel/src/createLdClient/createFeatureStore.ts
> +        .then((i) => {
Potentially you could just call an async function inside these, passing it the callback, and then not await it. So that the code could be structured using async/await.

Potentially we could add a more standard async feature of LDFeatureStore. I had just kept the interface largely the same for simplicity of porting existing stores.

I generally find async code much easier to follow and maintain. But this is just a thought/suggestion, not something that has to be changed.

2023-04-13 16:11 UTC, kinyoklion commented on packages/sdk/vercel/src/createLdClient/createOptions.ts
> +  sendEvents: false,
If vercel has fetch, then it should be possible. Not sure on the value, because I have not really been in the loop how we use these edge SDKs and why it is fine for them to not send events.

2023-04-13 16:49 UTC, monsagri commented on packages/sdk/vercel/src/platform/crypto/index.ts
> +    return uuidv4();
👍 thanks!

2023-04-14 13:55 UTC, InTheCloudDan commented on packages/sdk/vercel/src/createLdClient/createOptions.ts
> +  sendEvents: false,
I left a slack comment for @yusinto in regards to Cloudflare. When we go to enable `events` we want to also add in the `track` call. I'm not sure if it's waiting until `sendEvents` is usable to add that in.

2023-04-14 15:44 UTC, kinyoklion commented on packages/sdk/vercel/src/createLdClient/createOptions.ts
> +  sendEvents: false,
Yeah, we probably wouldn't want to add it before it actually sends events.

2023-04-18 13:17 UTC, yusinto commented
Please take a look at #83 which has the common code for cloudflare and vercel refactored to packages/shared/sdk-server-edge.

2023-04-18 13:21 UTC, monsagri commented
> Please take a look at #83 which has the common code for cloudflare and vercel refactored to packages/shared/sdk-server-edge.

Got it thanks! Actually had a scroll through already and will be making sure to get this updated today/tomorrow latest

Thanks for doing all the heavy lifting with the shared stuff!

2023-04-18 16:55 UTC, yusinto commented
> Thanks for doing all the heavy lifting with the shared stuff!

No worries! Thank you for doing the Vercel sdk. I have merged #83 now so you'll be able to use it from main which makes it easier.

2023-04-19 04:36 UTC, yusinto commented
Please take a look at #87 for producing cjs and esm bundles for the cloudflare sdk. TLDR your build command should use `scripts/build-package.sh` which will do the job. The [relevant code](https://github.com/launchdarkly/js-core/blob/5c45173edc67a9e4b0134a90320d337aef5f8de7/packages/sdk/cloudflare/package.json#L12) are:

```json
  "type": "module",
  "exports": {
    "require": "./dist/cjs/src/index.js",
    "import": "./dist/esm/src/index.js"
  },
  "main": "./dist/cjs/src/index.js",
  "types": "./dist/cjs/src/index.d.ts",
  "files": [
    "/dist"
  ],
  "scripts": {
    "build": "../../../scripts/build-package.sh",
```

2023-04-20 02:24 UTC, yusinto commented
The Cloudflare SDK 0.0.1 has been published. All code are in main now so you can safely follow the cloudflare sdk for vercel. Let me know if everything makes sense. Good luck!

2023-04-21 11:29 UTC, monsagri commented on packages/sdk/vercel/src/createLdClient/createFeatureStore.ts
> +        .then((i) => {
Not sure if I totally followed what you meant by not awaiting within the implementation here, but the change is an easy to revert commit and seems to work as expected.

2023-04-21 11:33 UTC, monsagri commented
I've made the changes that we talked about and adapted everything to use the new common modules where possible. 
Missing some tests against the main implementation for now using something like miniflare to mock the edge config, but think that can come as a follow up?

2023-04-22 05:24 UTC, yusinto requested changes
Nice work! I requested some changes but nothing serious.

You will also need to modify `release-please-config.json` for the initial publishing of this package. See [this](https://www.typescriptlang.org/tsconfig/#declaration).

2023-04-22 05:24 UTC, yusinto commented on packages/sdk/vercel/package.json
> +    "types": "./dist/esm/src/index.d.ts"
`types` can be omitted because typescript by default will look for definition files next to index.js.

2023-04-22 05:24 UTC, yusinto commented on packages/sdk/vercel/package.json
> +    "start": "yarn tsw",
You may want to clean the `dist` folder first before `yarn start`

2023-04-22 05:24 UTC, yusinto commented on packages/sdk/vercel/package.json
> +    "uuid": "^9.0.0"
`@launchdarkly/js-server-sdk-common` and `uuid` should be omitted because they are unused.

2023-04-22 05:24 UTC, yusinto commented on packages/sdk/vercel/package.json
> +    "@types/uuid": "^9.0.1",
`@types/uuid` should be omitted because uuid is unused.

2023-04-22 05:24 UTC, yusinto commented on packages/sdk/vercel/package.json
> +    "test": "jest --ci --runInBand",
Jest with coverage reveals that `index.ts` and `createPlatformInfo.ts` are completely untested. Are you able to add unit tests for those please?

```json
"test": "jest --ci --runInBand --coverage",
```

![Screenshot 2023-04-21 at 10 14 44 PM](https://user-images.githubusercontent.com/1593077/233764065-a3a6df45-9c75-48b3-bb25-28710b19763d.png)

2023-04-22 05:24 UTC, yusinto commented on package.json
> +    "packages/sdk/vercel"
If you have time, it will be good to add an example app to demo the basic usage of the vercel sdk.

2023-04-22 05:24 UTC, yusinto commented on scripts/build-package.sh
> +tsc --module es2022 --declaration --outDir dist/esm/
Is `--declaration` needed? I tested without and definition files are generated so I think they are unnecessary.

2023-04-24 09:11 UTC, monsagri commented on packages/sdk/vercel/package.json
> +    "types": "./dist/esm/src/index.d.ts"
I thought I needed them from testing the build output via npm link, but looks like I was wrong

2023-04-24 11:22 UTC, monsagri commented on packages/sdk/vercel/package.json
> +    "test": "jest --ci --runInBand",
Yep! 
Good shout, I've added them now and all files look better

2023-04-24 11:24 UTC, monsagri commented on package.json
> +    "packages/sdk/vercel"
Any chance we can do that as a follow up ticket? 

I'd like to get this merged for now so we can finalise the other work and get ready to release - we'll also need to set up a demo app for the vercel store page, so can bundle that work at that point.

2023-04-24 17:29 UTC, yusinto approved these changes

2023-04-25 11:27 UTC, merged